version: "3"
networks:
  default:
    driver: bridge
services:
  config-srv:
    image: xuxu123/config-srv
    environment:
      - MICRO_REGISTRY=${MICRO_REGISTRY}
      - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - default

  admin-api:
    image: xuxu123/admin-api
    environment:
      - MICRO_REGISTRY=${MICRO_REGISTRY}
      - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
    networks:
      - default

  agent-api:
    image: xuxu123/agent-api
    environment:
      - MICRO_REGISTRY=${MICRO_REGISTRY}
      - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
    networks:
      - default

  micro:
    image: xuxu123/micro
    environment:
      - MICRO_REGISTRY=${MICRO_REGISTRY}
      - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
    networks:
      - default
    ports:
      - 8080:8080



